# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 04:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('accountnumber', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phonenumber', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('coursename', models.CharField(max_length=100)),
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Time.Member')),
            ],
        ),
    ]
