# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='accountnumber',
            new_name='account',
        ),
    ]
