# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0002_auto_20180530_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Time.Seller')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Time.Member')),
            ],
        ),
    ]
