# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0003_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
